//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvvmapp.DTOServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ItemDTO", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceLibDto.DTOs", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class ItemDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private mvvmapp.DTOServiceReference.DetailDTO[] DetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImagePathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private mvvmapp.DTOServiceReference.OrderDTO[] OrdersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyField, value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public mvvmapp.DTOServiceReference.DetailDTO[] Details {
            get {
                return this.DetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailsField, value) != true)) {
                    this.DetailsField = value;
                    this.RaisePropertyChanged("Details");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImagePath {
            get {
                return this.ImagePathField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagePathField, value) != true)) {
                    this.ImagePathField = value;
                    this.RaisePropertyChanged("ImagePath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public mvvmapp.DTOServiceReference.OrderDTO[] Orders {
            get {
                return this.OrdersField;
            }
            set {
                if ((object.ReferenceEquals(this.OrdersField, value) != true)) {
                    this.OrdersField = value;
                    this.RaisePropertyChanged("Orders");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetailDTO", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceLibDto.DTOs")]
    [System.SerializableAttribute()]
    public partial class DetailDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImagePathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private mvvmapp.DTOServiceReference.ItemDTO ItemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ItemIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyField, value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImagePath {
            get {
                return this.ImagePathField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagePathField, value) != true)) {
                    this.ImagePathField = value;
                    this.RaisePropertyChanged("ImagePath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public mvvmapp.DTOServiceReference.ItemDTO Item {
            get {
                return this.ItemField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemField, value) != true)) {
                    this.ItemField = value;
                    this.RaisePropertyChanged("Item");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ItemId {
            get {
                return this.ItemIdField;
            }
            set {
                if ((this.ItemIdField.Equals(value) != true)) {
                    this.ItemIdField = value;
                    this.RaisePropertyChanged("ItemId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderDTO", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceLibDto.DTOs")]
    [System.SerializableAttribute()]
    public partial class OrderDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private mvvmapp.DTOServiceReference.ItemDTO[] OrderedComputersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SumField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public mvvmapp.DTOServiceReference.ItemDTO[] OrderedComputers {
            get {
                return this.OrderedComputersField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderedComputersField, value) != true)) {
                    this.OrderedComputersField = value;
                    this.RaisePropertyChanged("OrderedComputers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Sum {
            get {
                return this.SumField;
            }
            set {
                if ((this.SumField.Equals(value) != true)) {
                    this.SumField = value;
                    this.RaisePropertyChanged("Sum");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DTOServiceReference.IDTOService")]
    public interface IDTOService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDTOService/CreateItem", ReplyAction="http://tempuri.org/IDTOService/CreateItemResponse")]
        void CreateItem(mvvmapp.DTOServiceReference.ItemDTO elem, mvvmapp.DTOServiceReference.DetailDTO detail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDTOService/CreateItem", ReplyAction="http://tempuri.org/IDTOService/CreateItemResponse")]
        System.Threading.Tasks.Task CreateItemAsync(mvvmapp.DTOServiceReference.ItemDTO elem, mvvmapp.DTOServiceReference.DetailDTO detail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDTOService/UpdateItem", ReplyAction="http://tempuri.org/IDTOService/UpdateItemResponse")]
        void UpdateItem(mvvmapp.DTOServiceReference.ItemDTO elem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDTOService/UpdateItem", ReplyAction="http://tempuri.org/IDTOService/UpdateItemResponse")]
        System.Threading.Tasks.Task UpdateItemAsync(mvvmapp.DTOServiceReference.ItemDTO elem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDTOService/DeleteItem", ReplyAction="http://tempuri.org/IDTOService/DeleteItemResponse")]
        void DeleteItem(mvvmapp.DTOServiceReference.ItemDTO elem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDTOService/DeleteItem", ReplyAction="http://tempuri.org/IDTOService/DeleteItemResponse")]
        System.Threading.Tasks.Task DeleteItemAsync(mvvmapp.DTOServiceReference.ItemDTO elem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDTOService/GetItem", ReplyAction="http://tempuri.org/IDTOService/GetItemResponse")]
        mvvmapp.DTOServiceReference.ItemDTO GetItem(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDTOService/GetItem", ReplyAction="http://tempuri.org/IDTOService/GetItemResponse")]
        System.Threading.Tasks.Task<mvvmapp.DTOServiceReference.ItemDTO> GetItemAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDTOService/GetOrder", ReplyAction="http://tempuri.org/IDTOService/GetOrderResponse")]
        mvvmapp.DTOServiceReference.OrderDTO GetOrder(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDTOService/GetOrder", ReplyAction="http://tempuri.org/IDTOService/GetOrderResponse")]
        System.Threading.Tasks.Task<mvvmapp.DTOServiceReference.OrderDTO> GetOrderAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDTOService/GetAllItem", ReplyAction="http://tempuri.org/IDTOService/GetAllItemResponse")]
        mvvmapp.DTOServiceReference.ItemDTO[] GetAllItem();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDTOService/GetAllItem", ReplyAction="http://tempuri.org/IDTOService/GetAllItemResponse")]
        System.Threading.Tasks.Task<mvvmapp.DTOServiceReference.ItemDTO[]> GetAllItemAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDTOService/CreateOrder", ReplyAction="http://tempuri.org/IDTOService/CreateOrderResponse")]
        void CreateOrder(mvvmapp.DTOServiceReference.OrderDTO orderDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDTOService/CreateOrder", ReplyAction="http://tempuri.org/IDTOService/CreateOrderResponse")]
        System.Threading.Tasks.Task CreateOrderAsync(mvvmapp.DTOServiceReference.OrderDTO orderDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDTOService/GetOrderedComputers", ReplyAction="http://tempuri.org/IDTOService/GetOrderedComputersResponse")]
        mvvmapp.DTOServiceReference.OrderDTO[] GetOrderedComputers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDTOService/GetOrderedComputers", ReplyAction="http://tempuri.org/IDTOService/GetOrderedComputersResponse")]
        System.Threading.Tasks.Task<mvvmapp.DTOServiceReference.OrderDTO[]> GetOrderedComputersAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDTOServiceChannel : mvvmapp.DTOServiceReference.IDTOService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DTOServiceClient : System.ServiceModel.ClientBase<mvvmapp.DTOServiceReference.IDTOService>, mvvmapp.DTOServiceReference.IDTOService {
        
        public DTOServiceClient() {
        }
        
        public DTOServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DTOServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DTOServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DTOServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void CreateItem(mvvmapp.DTOServiceReference.ItemDTO elem, mvvmapp.DTOServiceReference.DetailDTO detail) {
            base.Channel.CreateItem(elem, detail);
        }
        
        public System.Threading.Tasks.Task CreateItemAsync(mvvmapp.DTOServiceReference.ItemDTO elem, mvvmapp.DTOServiceReference.DetailDTO detail) {
            return base.Channel.CreateItemAsync(elem, detail);
        }
        
        public void UpdateItem(mvvmapp.DTOServiceReference.ItemDTO elem) {
            base.Channel.UpdateItem(elem);
        }
        
        public System.Threading.Tasks.Task UpdateItemAsync(mvvmapp.DTOServiceReference.ItemDTO elem) {
            return base.Channel.UpdateItemAsync(elem);
        }
        
        public void DeleteItem(mvvmapp.DTOServiceReference.ItemDTO elem) {
            base.Channel.DeleteItem(elem);
        }
        
        public System.Threading.Tasks.Task DeleteItemAsync(mvvmapp.DTOServiceReference.ItemDTO elem) {
            return base.Channel.DeleteItemAsync(elem);
        }
        
        public mvvmapp.DTOServiceReference.ItemDTO GetItem(int id) {
            return base.Channel.GetItem(id);
        }
        
        public System.Threading.Tasks.Task<mvvmapp.DTOServiceReference.ItemDTO> GetItemAsync(int id) {
            return base.Channel.GetItemAsync(id);
        }
        
        public mvvmapp.DTOServiceReference.OrderDTO GetOrder(int id) {
            return base.Channel.GetOrder(id);
        }
        
        public System.Threading.Tasks.Task<mvvmapp.DTOServiceReference.OrderDTO> GetOrderAsync(int id) {
            return base.Channel.GetOrderAsync(id);
        }
        
        public mvvmapp.DTOServiceReference.ItemDTO[] GetAllItem() {
            return base.Channel.GetAllItem();
        }
        
        public System.Threading.Tasks.Task<mvvmapp.DTOServiceReference.ItemDTO[]> GetAllItemAsync() {
            return base.Channel.GetAllItemAsync();
        }
        
        public void CreateOrder(mvvmapp.DTOServiceReference.OrderDTO orderDTO) {
            base.Channel.CreateOrder(orderDTO);
        }
        
        public System.Threading.Tasks.Task CreateOrderAsync(mvvmapp.DTOServiceReference.OrderDTO orderDTO) {
            return base.Channel.CreateOrderAsync(orderDTO);
        }
        
        public mvvmapp.DTOServiceReference.OrderDTO[] GetOrderedComputers() {
            return base.Channel.GetOrderedComputers();
        }
        
        public System.Threading.Tasks.Task<mvvmapp.DTOServiceReference.OrderDTO[]> GetOrderedComputersAsync() {
            return base.Channel.GetOrderedComputersAsync();
        }
    }
}
