//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvvmapp.ServiceReference2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ItemDTO", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceLibDto.DTOs")]
    [System.SerializableAttribute()]
    public partial class ItemDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImagePathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyField, value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImagePath {
            get {
                return this.ImagePathField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagePathField, value) != true)) {
                    this.ImagePathField = value;
                    this.RaisePropertyChanged("ImagePath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IItemDTOService")]
    public interface IItemDTOService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IItemDTOService/Create", ReplyAction="http://tempuri.org/IItemDTOService/CreateResponse")]
        void Create(mvvmapp.ServiceReference2.ItemDTO elem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IItemDTOService/Create", ReplyAction="http://tempuri.org/IItemDTOService/CreateResponse")]
        System.Threading.Tasks.Task CreateAsync(mvvmapp.ServiceReference2.ItemDTO elem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IItemDTOService/Update", ReplyAction="http://tempuri.org/IItemDTOService/UpdateResponse")]
        void Update(mvvmapp.ServiceReference2.ItemDTO elem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IItemDTOService/Update", ReplyAction="http://tempuri.org/IItemDTOService/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(mvvmapp.ServiceReference2.ItemDTO elem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IItemDTOService/Delete", ReplyAction="http://tempuri.org/IItemDTOService/DeleteResponse")]
        void Delete(mvvmapp.ServiceReference2.ItemDTO elem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IItemDTOService/Delete", ReplyAction="http://tempuri.org/IItemDTOService/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(mvvmapp.ServiceReference2.ItemDTO elem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IItemDTOService/Get", ReplyAction="http://tempuri.org/IItemDTOService/GetResponse")]
        void Get(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IItemDTOService/Get", ReplyAction="http://tempuri.org/IItemDTOService/GetResponse")]
        System.Threading.Tasks.Task GetAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IItemDTOService/GetAll", ReplyAction="http://tempuri.org/IItemDTOService/GetAllResponse")]
        mvvmapp.ServiceReference2.ItemDTO[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IItemDTOService/GetAll", ReplyAction="http://tempuri.org/IItemDTOService/GetAllResponse")]
        System.Threading.Tasks.Task<mvvmapp.ServiceReference2.ItemDTO[]> GetAllAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IItemDTOServiceChannel : mvvmapp.ServiceReference2.IItemDTOService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ItemDTOServiceClient : System.ServiceModel.ClientBase<mvvmapp.ServiceReference2.IItemDTOService>, mvvmapp.ServiceReference2.IItemDTOService {
        
        public ItemDTOServiceClient() {
        }
        
        public ItemDTOServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ItemDTOServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ItemDTOServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ItemDTOServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Create(mvvmapp.ServiceReference2.ItemDTO elem) {
            base.Channel.Create(elem);
        }
        
        public System.Threading.Tasks.Task CreateAsync(mvvmapp.ServiceReference2.ItemDTO elem) {
            return base.Channel.CreateAsync(elem);
        }
        
        public void Update(mvvmapp.ServiceReference2.ItemDTO elem) {
            base.Channel.Update(elem);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(mvvmapp.ServiceReference2.ItemDTO elem) {
            return base.Channel.UpdateAsync(elem);
        }
        
        public void Delete(mvvmapp.ServiceReference2.ItemDTO elem) {
            base.Channel.Delete(elem);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(mvvmapp.ServiceReference2.ItemDTO elem) {
            return base.Channel.DeleteAsync(elem);
        }
        
        public void Get(int id) {
            base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task GetAsync(int id) {
            return base.Channel.GetAsync(id);
        }
        
        public mvvmapp.ServiceReference2.ItemDTO[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<mvvmapp.ServiceReference2.ItemDTO[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
    }
}
